from: ${PROFZONE_DOCKER_REGISTRY}/profzone/golang:runtime
image: ${PROFZONE_DOCKER_REGISTRY}/${PROJECT_GROUP}/${PROJECT_NAME}:${PROJECT_VERSION}
workdir: /go/bin
env:
  GOENV: DEV
  S_LOG_FORMAT: json
  S_SERVER_PORT: "80"
  S_SERVER_WITHCORS: "false"
add:
  ./config: ./config
  ./profzone.yml: ./
  ./service-id: ./
  ./swagger.json: ./
expose:
- "80"
cmd:
- ./service-id
- -c=false
